### ISSUE TITLE
question about cloning the capsule

### ISSUE THREAD

**Issue by magland** [AllenNeuralDynamics/aind-ephys-pipeline#22]
Hi, I'd like to access the source code of the capsule. From the .nf file it seems to be at

https://\$GIT_ACCESS_TOKEN@\$GIT_HOST/capsule-0874799.git

How can I get that?

**Comment by alejoe91** [comment]
Hi @magland 

All capsules are linked in the readme and you can also find the individual capsule repos from the `main_local.nf` and `main_slurm.nf`

The `main.nf` is what we use internally through Code Ocean
